import swaggerAutogen from 'swagger-autogen';
import 'dotenv/config';

const ENVIRONMENT = process.env.NODE_ENV || 'development';
const PORT = process.env.PORT || 3000;
const outputFile = './swagger_output.json';
const endpointsFiles = ['./server.js'];
const isProduction = ENVIRONMENT === 'production';

const docs = {
  info: {
    version: "1.0.0",
    title: "Node Labs",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: isProduction ? 'https://monkfish-app-kfd4z.ondigitalocean.app/' : `http://localhost:${PORT}`,
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "Users",
      "description": "Endpoints"
    }
  ]
};

/*
name: string
username: string
email: string
avatar: string
sexType: string
password: string
birthdate: string
registeredAt: string
*/

swaggerAutogen(outputFile, endpointsFiles, docs);