import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json';
const endpointsFiles = ['./server.js'];

const docs = {
  info: {
    version: "1.0.0",
    title: "Node Labs",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "Users",
      "description": "Endpoints"
    }
  ]
};

/*
name: string
username: string
email: string
avatar: string
sexType: string
password: string
birthdate: string
registeredAt: string
*/

swaggerAutogen(outputFile, endpointsFiles, docs);